In [1]:
import pandas as pd

In [11]:
food_sample_100 = pd.read_csv('food_sample_100.csv')
food_other = pd.read_csv('food_other.csv')
food_nutrient =  pd.read_csv('food_nutrient.csv')
branded_food = pd.read_csv('branded_food.csv')

In [ ]:
food = pd.concat([food_sample_100, food_other], ignore_index=True)
# takhle mají indexi kazdá nechaný a když doplním ignore - tak už je jen index jeden společný
food
# toto odpovídá v sql funkci union (že je narveme na sebe)

,fdc_id,data_type,description,food_category_id,publication_date
0,2644829,sub_sample_food,"lentils, dry",16.0,2023-10-19
1,2347263,sub_sample_food,heavy cream,1.0,2022-10-28
2,2261954,sub_sample_food,"Flour, potato",11.0,2022-04-28
3,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01
4,322951,sub_sample_food,Hot dogs beef,7.0,2019-04-01
...,...,...,...,...,...
9995,2661515,branded_food,"CHAI LATTE SUGAR FREE BLACK TEA CONCENTRATE, C...",NaN,2023-10-26
9996,2661730,branded_food,"APPLE BANANA ORGANIC FRUIT POUCHES, APPLE BANANA",NaN,2023-10-26
9997,2661782,branded_food,"SPINACH ORGANIC PUREE, SPINACH",NaN,2023-10-26
9998,2662107,branded_food,LIGHT MOZZARELLA LOW-MOISTURE PART-SKIM STRING...,NaN,2023-10-26
9999,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26

In [ ]:
# ted bude podobná operace jako join v sql - spojíme dvě tabulky k sobě pomocí klíče - merge

food_merged = pd.merge(food, food_nutrient, on="fdc_id")
# pokud se každý sloupec jmenuje jinak (ten podle kterého to chci spojit), tak dám (left_on="fdc_id", right_on="id")
# toto je automaticky inner join, pokud chci left, right nebo outer dopíšu čárku, how="left")
food_merged

,fdc_id,data_type,description,food_category_id,publication_date,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
0,2644829,sub_sample_food,"lentils, dry",16.0,2023-10-19,1101,1.58,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,"Manganese, Mn",MG
1,2347263,sub_sample_food,heavy cream,1.0,2022-10-28,1258,20.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total saturated",G
2,2261954,sub_sample_food,"Flour, potato",11.0,2022-04-28,1102,21.80,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,"Molybdenum, Mo",UG
3,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01,1051,0.69,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Water,G
4,321470,sub_sample_food,"Salt, Iodized",2.0,2019-04-01,1007,98.40,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Ash,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135331,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1005,4.07,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Carbohydrate, by difference",G
135332,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1004,0.41,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Total lipid (fat),G
135333,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1003,0.81,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Protein,G
135334,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1235,0.00,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sugars, added",G
135335,2662182,branded_food,"ITALIAN-STYLE DICED TOMATOES WITH BASIL, GARLI...",NaN,2023-10-26,1114,0.00,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin D (D2 + D3),UG

In [ ]:
branded_food.head()
branded_food.columns()
branded_food['brand_owner'].value_counts().head(3)
branded_food['branded_food_category'].value_counts().head(5)

In [ ]:
branded_food
# 135336 rows × 17 columns počet před spojením
food_merged_brands = pd.merge(branded_food, food_merged, on="fdc_id", how="right")
# food_merged_brands = pd.merge(food_merged, branded_food, right_on="fdc_id", left_on="fdc_id")
# toto je řešení z githubu (já dala jen obráceně)
food_merged_brands
# 129284 rows × 36 columns počet bez how 
# 129284 rows × 36 columns s left join
# 135336 rows × 36 columns s right join

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,...,data_points,derivation_id,min,max,median,loq,footnote,min_year_acquired,name,unit_name
0,2644829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,"Manganese, Mn",MG
1,2347263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,"Fatty acids, total saturated",G
2,2261954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,"Molybdenum, Mo",UG
3,321470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Water,G
4,321470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,Ash,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135331,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Carbohydrate, by difference",G
135332,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Total lipid (fat),G
135333,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Protein,G
135334,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,"Sugars, added",G
135335,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,NaN,70.0,NaN,NaN,NaN,NaN,NaN,NaN,Vitamin D (D2 + D3),UG

In [27]:
food_merged_brands = food_merged_brands.rename(columns={"name": "nutrient_name"})
# přejmenování sloupce
food_merged_brands

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,...,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,nutrient_name,unit_name
0,2644829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1101,1.58,1.0,1.0,NaN,NaN,NaN,NaN,"Manganese, Mn",MG
1,2347263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1258,20.00,1.0,1.0,NaN,NaN,NaN,NaN,"Fatty acids, total saturated",G
2,2261954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1102,21.80,1.0,1.0,NaN,NaN,NaN,NaN,"Molybdenum, Mo",UG
3,321470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1051,0.69,1.0,1.0,NaN,NaN,NaN,NaN,Water,G
4,321470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1007,98.40,1.0,1.0,NaN,NaN,NaN,NaN,Ash,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135331,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1005,4.07,NaN,70.0,NaN,NaN,NaN,NaN,"Carbohydrate, by difference",G
135332,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1004,0.41,NaN,70.0,NaN,NaN,NaN,NaN,Total lipid (fat),G
135333,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1003,0.81,NaN,70.0,NaN,NaN,NaN,NaN,Protein,G
135334,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1235,0.00,NaN,70.0,NaN,NaN,NaN,NaN,"Sugars, added",G
135335,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1114,0.00,NaN,70.0,NaN,NaN,NaN,NaN,Vitamin D (D2 + D3),UG

In [ ]:
food_merged_brands = food_merged_brands.drop(columns=["footnote", "min_year_acquired"])
# mazání sloupců
food_merged_brands

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,...,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,nutrient_name,unit_name
0,2644829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1101,1.58,1.0,1.0,NaN,NaN,NaN,NaN,"Manganese, Mn",MG
1,2347263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1258,20.00,1.0,1.0,NaN,NaN,NaN,NaN,"Fatty acids, total saturated",G
2,2261954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1102,21.80,1.0,1.0,NaN,NaN,NaN,NaN,"Molybdenum, Mo",UG
3,321470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1051,0.69,1.0,1.0,NaN,NaN,NaN,NaN,Water,G
4,321470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1007,98.40,1.0,1.0,NaN,NaN,NaN,NaN,Ash,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135331,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1005,4.07,NaN,70.0,NaN,NaN,NaN,NaN,"Carbohydrate, by difference",G
135332,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1004,0.41,NaN,70.0,NaN,NaN,NaN,NaN,Total lipid (fat),G
135333,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1003,0.81,NaN,70.0,NaN,NaN,NaN,NaN,Protein,G
135334,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1235,0.00,NaN,70.0,NaN,NaN,NaN,NaN,"Sugars, added",G
135335,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1114,0.00,NaN,70.0,NaN,NaN,NaN,NaN,Vitamin D (D2 + D3),UG

In [30]:
food_merged_brands

,fdc_id,brand_owner,brand_name,subbrand_name,gtin_upc,ingredients,not_a_significant_source_of,serving_size,serving_size_unit,household_serving_fulltext,...,nutrient_id,amount,data_points,derivation_id,min,max,median,loq,nutrient_name,unit_name
0,2644829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1101,1.58,1.0,1.0,NaN,NaN,NaN,NaN,"Manganese, Mn",MG
1,2347263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1258,20.00,1.0,1.0,NaN,NaN,NaN,NaN,"Fatty acids, total saturated",G
2,2261954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1102,21.80,1.0,1.0,NaN,NaN,NaN,NaN,"Molybdenum, Mo",UG
3,321470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1051,0.69,1.0,1.0,NaN,NaN,NaN,NaN,Water,G
4,321470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1007,98.40,1.0,1.0,NaN,NaN,NaN,NaN,Ash,G
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135331,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1005,4.07,NaN,70.0,NaN,NaN,NaN,NaN,"Carbohydrate, by difference",G
135332,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1004,0.41,NaN,70.0,NaN,NaN,NaN,NaN,Total lipid (fat),G
135333,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1003,0.81,NaN,70.0,NaN,NaN,NaN,NaN,Protein,G
135334,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1235,0.00,NaN,70.0,NaN,NaN,NaN,NaN,"Sugars, added",G
135335,2662182,Target Stores,GOOD & GATHER,NaN,8.523911e+10,"TOMATOES, TOMATO JUICE, LESS THAN 2% OF: SALT,...",NaN,123.0,GRM,1/2 cup,...,1114,0.00,NaN,70.0,NaN,NaN,NaN,NaN,Vitamin D (D2 + D3),UG

In [32]:
# kod od lektorky

food_merged_brands = pd.merge(food_merged, branded_food, right_on="fdc_id", left_on="fdc_id", how="left")
food_merged_brands = food_merged_brands.rename(columns={"name": "nutrient_name"})
food_merged_brands = food_merged_brands.drop(columns=['data_points', 'min', 'max', 'median', 'loq', 'min_year_acquired', 'derivation_id', 'footnote', 
                                                      'publication_date', 'subbrand_name','gtin_upc','ingredients', 'not_a_significant_source_of', 
                                                      'serving_size','serving_size_unit', 'household_serving_fulltext','data_source', 'package_weight',
                                                      'modified_date', 'available_date', 'market_country','discontinued_date', 'preparation_state_code', 
                                                      'trade_channel', 'short_description'])

In [36]:
# dataframe.groupby("sloupecek_pro_sgrupovani")["sloupecek_pro_pocitani"].sum()
# toto je v podstatě group by a sum v sql
food_merged_brands.groupby("branded_food_category")["amount"].sum()

branded_food_category
Alcohol                          45633.630
Alcoholic Beverages                106.000
All Noodles                      20143.491
Baby/Infant  Foods/Beverages       454.060
Bacon                             1937.600
                                   ...
Weight Control                    1388.009
Wholesome Snacks                207696.830
Yogurt                          103095.607
Yogurt (Perishable)               5327.470
Yogurt/Yogurt Substitutes         8776.240
Name: amount, Length: 194, dtype: float64

In [37]:
food_merged_brands.groupby("branded_food_category")["amount"].mean()

branded_food_category
Alcohol                         211.266806
Alcoholic Beverages              53.000000
All Noodles                      70.927785
Baby/Infant  Foods/Beverages     16.817037
Bacon                           176.145455
                                   ...
Weight Control                   43.375281
Wholesome Snacks                126.490152
Yogurt                           40.052683
Yogurt (Perishable)             332.966875
Yogurt/Yogurt Substitutes        48.487514
Name: amount, Length: 194, dtype: float64

In [39]:
food_merged_brands_protein = food_merged_brands[food_merged_brands["nutrient_name"] == "Protein"]
food_merged_brands_protein.groupby("branded_food_category")["amount"].mean().sort_values(ascending=False).head(10)

branded_food_category
Bacon                                                  45.200000
Green Supplements                                      44.590000
Drinks Flavoured - Ready to Drink                      32.900000
Energy, Protein & Muscle Recovery Drinks               31.831481
Bacon, Sausages & Ribs                                 27.239630
Canned Tuna                                            21.648889
Meat/Poultry/Other Animals  Prepared/Processed         21.522368
Nut & Seed Butters                                     20.651270
Cheese                                                 19.969457
Meat/Poultry/Other Animals – Unprepared/Unprocessed    19.640000
Name: amount, dtype: float64

In [41]:
food_merged_brands_protein_agg = food_merged_brands_protein.groupby("branded_food_category")["amount"].mean()
food_merged_brands_protein_agg.sort_values(ascending=False).head(10)

branded_food_category
Bacon                                                  45.200000
Green Supplements                                      44.590000
Drinks Flavoured - Ready to Drink                      32.900000
Energy, Protein & Muscle Recovery Drinks               31.831481
Bacon, Sausages & Ribs                                 27.239630
Canned Tuna                                            21.648889
Meat/Poultry/Other Animals  Prepared/Processed         21.522368
Nut & Seed Butters                                     20.651270
Cheese                                                 19.969457
Meat/Poultry/Other Animals – Unprepared/Unprocessed    19.640000
Name: amount, dtype: float64